name: Compile and Deploy Resume

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/xu-cheng/texlive-full:latest  # Pre-installed TeX Live
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: |
          apt-get update
          apt-get install -y openssh-client

      - name: Compile LaTeX
        run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error resume.tex
          ls -lh

      - name: Deploy to GitHub Pages
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git checkout --orphan gh-pages
          git reset --hard
          mv resume.pdf index.pdf
          git add index.pdf
          git commit -m "Deploy latest resume.pdf"
          git push --force git@github.com:${{ github.repository }}.git gh-pages
