
name: Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Compile and Deploy
        uses: jonhue/pubtex-action@v1.1.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          files: |
            resume.tex
